version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk11
    commands:
      - pip3 install aws-sam-cli
  pre_build:
    commands:
      - export LC_ALL="en_US.UTF-8"
      - locale-gen en_US en_US.UTF-8
      - dpkg-reconfigure locales
  build:
    commands:
      - ./gradlew :search-commons:clean :search-commons:build
      - sam build
      - sam package --s3-bucket $S3_BUCKET --output-template-file packaged.yaml
artifacts:
  files:
    - packaged.yaml