AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  NVA Search Resources API and Handler

Globals:
  Function:
    Timeout: 60
    MemorySize: 1800
    Environment:
      Variables:
        COGNITO_URI: !Ref CognitoUri
  Api:
    Cors:
      AllowMethods: "'PUT, GET,OPTIONS,DELETE,POST'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      AllowOrigin: "'*'"

Parameters:
  CognitoUri:
    Type: AWS::SSM::Parameter::Value<String>
    Description: Reference to Cognito Auth URI
    Default: /NVA/CognitoUri
  CognitoAuthorizerArn:
    Type: AWS::SSM::Parameter::Value<String>
    Description: Reference to Cognito UserPool for the stage
    Default: CognitoAuthorizerArn
  CustomDomain:
    Type: AWS::SSM::Parameter::Value<String>
    Description: Custom API to connect this lambda to
    Default: CustomDomain
  CustomDomainBasePath:
    Type: String
    Description: Base path mapping in CustomDomain
    Default: search
  EventBusName:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /NVA/Events/EventsBusName
  EventBusArn:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /NVA/Events/EventsBusArn
  ResourcesBucket:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /NVA/Events/PersistedEntriesBucketName
  MaxConcurrency:
    Type: String
    Description: Maximum capacity for provisioned concurrency
    Default: 10
  MinConcurrency:
    Type: String
    Description: Minimum capacity for provisioned concurrency
    Default: 1
  Suffix:
    Type: String
    Default: ''
    Description: Suffix used for naming resources for feature branches to avoid conflicts.
  ElasticSearchSize:
    Type: String
    AllowedValues:
      - small
      - large



Conditions:
  WithSuffix: !Not [ !Equals [ !Ref Suffix, '' ] ]
  LargeElasticSearch:  !Equals [ !Ref ElasticSearchSize, 'large' ]


Resources:
  ApiAccessLogGroup:
    Type: AWS::Logs::LogGroup

  ReadOnlyAccessElasticSearchRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: [ lambda.amazonaws.com ]
            Action: [ 'sts:AssumeRole' ]
      Policies:
        - PolicyName: writeLog
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:*:*'
        - PolicyName: readIdentitySecret
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:IdentityServiceSecret*'

  ReadOnlyAccessS3Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: [ lambda.amazonaws.com ]
            Action: [ 'sts:AssumeRole' ]
      Policies:
        - PolicyName: readFromS3
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:Get*
                  - s3:List*
                  - events:*
                Resource: '*'
        - PolicyName: writeLog
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:*:*'
        - PolicyName: writetoelasticsearch
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - es:ESHttpPost
                  - es:ESHttpPut
                Resource: !Sub 'arn:aws:es:${AWS::Region}:${AWS::AccountId}:domain/*'

  NVAElasticSearch:
    Type: AWS::Elasticsearch::Domain
    Properties:
      AccessPolicies:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !GetAtt TriggerExecutionRole.Arn
            Action: 'es:*'
            Resource: !Sub 'arn:aws:es:${AWS::Region}:${AWS::AccountId}:domain/*'
          - Effect: Allow
            Principal:
              AWS: !GetAtt ReadOnlyAccessElasticSearchRole.Arn
            Action:
              - es:ESHttpPost
              - es:ESHttpGet
              - es:ESHttpPut
              - es:ESHttpHead
            Resource: !Sub 'arn:aws:es:${AWS::Region}:${AWS::AccountId}:domain/*'
      ElasticsearchClusterConfig: !If [ LargeElasticSearch,
        {
            DedicatedMasterEnabled: true,
            DedicatedMasterType: t2.medium.elasticsearch,
            DedicatedMasterCount: 3,
            InstanceCount: 2,
            ZoneAwarenessEnabled: false,
            InstanceType: t2.medium.elasticsearch
        },
        {
          DedicatedMasterEnabled: false,
          InstanceCount: 1,
          ZoneAwarenessEnabled: false,
          InstanceType: t2.medium.elasticsearch
        }
      ]
      ElasticsearchVersion: '7.10'
      EBSOptions:
        EBSEnabled: true
        VolumeSize: 10
        VolumeType: gp2
      CognitoOptions:
        Enabled: false

  NvaSearchApi:
    Type: AWS::Serverless::Api
    Properties:
      AccessLogSetting:
        DestinationArn: !GetAtt ApiAccessLogGroup.Arn
        Format: '{ "apiId": "$context.apiId", "requestId": "$context.requestId", "requestTime": "$context.requestTime", "requestTimeEpoch": "$context.requestTimeEpoch", "httpMethod": "$context.httpMethod", "path": "$context.path", "status": "$context.status",  "error.message": "$context.error.message" }'
      StageName: Prod
      EndpointConfiguration: REGIONAL
      DefinitionBody:
        'Fn::Transform':
          Name: 'AWS::Include'
          Parameters:
            Location: ./docs/openapi.yaml

  CustomCodeDeployServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service: [ codedeploy.amazonaws.com ]
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSCodeDeployRoleForLambda

  SearchFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: search-resources-api
      Handler: no.unit.nva.search.SearchResourcesApiHandler::handleRequest
      Runtime: java11
      AutoPublishAlias: live
      DeploymentPreference:
        Enabled: true
        Role: !GetAtt CustomCodeDeployServiceRole.Arn
        Type: AllAtOnce
      ProvisionedConcurrencyConfig:
        ProvisionedConcurrentExecutions: 1
      Role: !GetAtt ReadOnlyAccessElasticSearchRole.Arn
      Environment:
        Variables:
          ALLOWED_ORIGIN: '*'
          ELASTICSEARCH_ENDPOINT_ADDRESS: !GetAtt NVAElasticSearch.DomainEndpoint
          ELASTICSEARCH_REGION: !Ref "AWS::Region"
      Events:
        GetResources:
          Type: Api
          Properties:
            Path: /resources
            Method: get
            RestApiId: !Ref NvaSearchApi
        GetMessages:
          Type: Api
          Properties:
            Path: /messages
            Method: get
            RestApiId: !Ref NvaSearchApi
        GetTickets:
          Type: Api
          Properties:
            Path: /tickets
            Method: get
            RestApiId: !Ref NvaSearchApi
        GetDoiRequests:
          Type: Api
          Properties:
            Path: /doirequests
            Method: get
            RestApiId: !Ref NvaSearchApi

  NvaWorklistHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: search-resources-api
      Handler: no.unit.nva.search.SearchAllHandler::handleRequest
      Runtime: java11
      Role: !GetAtt ReadOnlyAccessElasticSearchRole.Arn
      Environment:
        Variables:
          ALLOWED_ORIGIN: '*'
          ELASTICSEARCH_ENDPOINT_ADDRESS: !GetAtt NVAElasticSearch.DomainEndpoint
          ELASTICSEARCH_REGION: !Ref "AWS::Region"
          IDENTITY_SERVICE_SECRET_NAME: 'IdentityServiceSecret-' #TODO update when secret name is updated
          IDENTITY_SERVICE_SECRET_KEY: 'IdentityServiceSecretKey'
          API_HOST: !Sub 'api.${CustomDomain}'
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /worklist
            Method: get
            RestApiId: !Ref NvaSearchApi


  SearchResourcesApiFunctionScalableTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Properties:
      MaxCapacity: !Ref MaxConcurrency
      MinCapacity: !Ref MinConcurrency
      ResourceId: !Sub function:${SearchFunction}:live
      RoleARN: !Sub arn:aws:iam::${AWS::AccountId}:role/aws-service-role/lambda.application-autoscaling.amazonaws.com/AWSServiceRoleForApplicationAutoScaling_LambdaConcurrency
      ScalableDimension: lambda:function:ProvisionedConcurrency
      ServiceNamespace: lambda
    DependsOn: SearchFunctionAliaslive

  SearchResourcesApiFunctionScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: utilization
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref   SearchResourcesApiFunctionScalableTarget
      TargetTrackingScalingPolicyConfiguration:
        TargetValue: 0.70
        PredefinedMetricSpecification:
          PredefinedMetricType: LambdaProvisionedConcurrencyUtilization


  NvaPublicationBasePathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      BasePath:
        !If
        - WithSuffix
        - !Sub ${CustomDomainBasePath}-${Suffix}
        - !Sub ${CustomDomainBasePath}
      DomainName: !Sub api.${CustomDomain}
      RestApiId: !Ref NvaSearchApi
      Stage: !Ref NvaSearchApi.Stage

  # ------------------------------------------------------
  #  Setup for EventBridge trigger
  # ------------------------------------------------------

  TriggerExecutionRole:
    DependsOn:
      - ResourcesIndexerDLQ
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: [ lambda.amazonaws.com ]
            Action: [ 'sts:AssumeRole' ]
      Path: /
      Policies:
        - PolicyName: writeLog
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:*:*"
        - PolicyName: Events
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - events:*
                  - sqs:SendMessage
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                Resource:
                  - !Ref EventBusArn
                  - !GetAtt BatchIndexEventBus.Arn
                  - !GetAtt ResourcesIndexerDLQ.Arn
        - PolicyName: readFromS3
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:Get*
                  - s3:List*
                  - events:*
                Resource: '*'

  IndexResources:
    DependsOn:
      - ResourcesIndexerDLQ
      - TriggerExecutionRole
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: indexing-handlers
      Handler: no.unit.nva.indexing.handlers.IndexResourceHandler::handleRequest
      Runtime: java11
      ReservedConcurrentExecutions: 32
      Role: !GetAtt TriggerExecutionRole.Arn
      MemorySize: 1408
      Environment:
        Variables:
          ELASTICSEARCH_ENDPOINT_ADDRESS: !GetAtt NVAElasticSearch.DomainEndpoint
          ELASTICSEARCH_REGION: !Ref "AWS::Region"
          EXPANDED_RESOURCES_BUCKET: !Ref ResourcesBucket
      Events:
        EventBridgeEvent:
          Type: EventBridgeRule
          Properties:
            EventBusName:
              Ref: EventBusName
            Pattern:
              detail-type:
                - Lambda Function Invocation Result - Success
              detail:
                responsePayload:
                  topic: [ "PublicationService.ExpandedEntry.Persisted" ]


  ResourcesIndexerDLQ:
    Type: AWS::SQS::Queue

  EventBasedBatchIndex:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: batch-index
      Handler: no.unit.nva.search.EventBasedBatchIndexer::handleRequest
      Runtime: java11
      MemorySize: 10240
      Timeout: 900
      Role: !GetAtt ReadOnlyAccessS3Role.Arn
      Events:
        BatchIndexEvent:
          Type: EventBridgeRule
          Properties:
            EventBusName: !GetAtt BatchIndexEventBus.Name
            Pattern:
              detail:
                topic: [ "SearchService.Index.Batch" ]
      Environment:
        Variables:
          ALLOWED_ORIGIN: '*'
          ELASTICSEARCH_ENDPOINT_ADDRESS: !GetAtt NVAElasticSearch.DomainEndpoint
          ELASTICSEARCH_REGION: !Ref "AWS::Region"
          BATCH_INDEX_EVENT_BUS_NAME: !GetAtt BatchIndexEventBus.Name

  BatchIndexingFromS3:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: batch-index
      Handler: no.unit.nva.search.ImportToSearchIndexHandler::handleRequest
      Runtime: java11
      MemorySize: 1024
      Timeout: 900
      Role: !GetAtt ReadOnlyAccessS3Role.Arn
      Environment:
        Variables:
          ALLOWED_ORIGIN: '*'
          ELASTICSEARCH_ENDPOINT_ADDRESS: !GetAtt NVAElasticSearch.DomainEndpoint
          ELASTICSEARCH_REGION: !Ref "AWS::Region"
          BATCH_INDEX_EVENT_BUS_NAME: !GetAtt BatchIndexEventBus.Name

  BatchIndexEventBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: !If
        - WithSuffix
        - !Join [ "-",[ "BatchIndexEventBus", !Ref Suffix ] ]
        - "BatchIndexEventBus"

  InitHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: indexing-handlers
      Handler: no.unit.nva.indexing.handlers.InitHandler::handleRequest
      Runtime: java11
      MemorySize: 1024
      Role: !GetAtt ReadOnlyAccessS3Role.Arn
      Environment:
        Variables:
          ELASTICSEARCH_ENDPOINT_ADDRESS: !GetAtt NVAElasticSearch.DomainEndpoint
          ELASTICSEARCH_REGION: !Ref "AWS::Region"