plugins {
    id 'nva.search.service.java-conventions'
}

dependencies {
    api(libs.opensearch)
    api(nvaCatalog.aws.sdk2.sqs)
    api(nvaCatalog.jackson.databind)
    api(nvaCatalog.mockito.core)
    api(project(":search-commons"))
    implementation(nvaCatalog.com.auth0.jwt)
    implementation(nvaCatalog.jackson.core)
    implementation(nvaCatalog.log4j.core)
    implementation(nvaLibs.core)
    implementation(nvaLibs.json)
}
